# Generated by Django 4.2.2 on 2023-06-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JosaaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.TextField()),
                ('program', models.TextField()),
                ('quota', models.CharField(max_length=20)),
                ('seatType', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=200)),
                ('openrank', models.CharField(max_length=10)),
                ('closerank', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=5)),
                ('round', models.CharField(max_length=2)),
            ],
        ),
    ]
