# Generated by Django 4.2.2 on 2023-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='josaadata',
            name='institute',
            field=models.CharField(max_length=100000),
        ),
    ]
