# Generated by Django 4.2.2 on 2023-07-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_alter_josaadata_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100000)),
            ],
        ),
        migrations.AlterField(
            model_name='josaadata',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyser.institutes'),
        ),
        migrations.AlterField(
            model_name='josaadata',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyser.branch'),
        ),
    ]
