# Generated by Django 4.2.2 on 2023-07-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0003_branch_institutes_alter_josaadata_institute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='institutes',
            old_name='institute',
            new_name='name',
        ),
    ]
