# Generated by Django 4.2.2 on 2023-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100000)),
                ('program', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('seatType', models.CharField(max_length=100)),
                ('open', models.IntegerField()),
                ('openpwd', models.IntegerField()),
                ('ews', models.IntegerField()),
                ('ewspwd', models.IntegerField()),
                ('sc', models.IntegerField()),
                ('scpwd', models.IntegerField()),
                ('st', models.IntegerField()),
                ('stpwd', models.IntegerField()),
                ('obc', models.IntegerField()),
                ('obcpwd', models.IntegerField()),
                ('total', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('female_supnum', models.IntegerField()),
            ],
        ),
    ]
